import { StyleSheet } from 'react-native';
import { COLORS } from '../../theme/theme';

export const cartStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  main: {
    flex: 1,
  },
  emptyContent: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  emptyIllustrationContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 40,
    width: 280,
    height: 280,
  },
  emptyCircleBackground: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: COLORS.secondary,
    opacity: 0.3,
    transform: [{ scale: 0.8 }],
  },
  emptyIconContainer: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.2,
    shadowRadius: 30,
    elevation: 20,
    zIndex: 10,
  },
  emptyDecoratorCircle1: {
    position: 'absolute',
    top: 40,
    right: 40,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: COLORS.accent,
    opacity: 0.6,
  },
  emptyDecoratorCircle2: {
    position: 'absolute',
    bottom: 60,
    left: 50,
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: COLORS.primary,
    opacity: 0.4,
  },
  emptyTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: COLORS.textPrimary,
    marginBottom: 12,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  emptySubtitle: {
    fontSize: 16,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 48,
    paddingHorizontal: 32,
    opacity: 0.8,
  },
  startShoppingButton: {
    width: '100%',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
    borderRadius: 28,
    overflow: 'visible', // allow shadow
  },
  startShoppingGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 56,
    borderRadius: 28,
    gap: 12,
  },
  startShoppingText: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.white,
    letterSpacing: 0.5,
  },
  header: {
    position: 'relative',
    backgroundColor: `${COLORS.background}CC`,
  },
  headerGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 6,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 24,
    paddingBottom: 16,
    paddingHorizontal: 16,
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.textPrimary,
    flex: 1,
    textAlign: 'center',
  },
  itemsList: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 16,
  },
  itemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    padding: 12,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 5,
    gap: 16,
  },
  itemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 16,
  },
  itemImage: {
    width: 64,
    height: 64,
    borderRadius: 12,
    backgroundColor: '#f0f0f0',
  },
  itemDetails: {
    flex: 1,
    justifyContent: 'center',
  },
  itemName: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  itemPrice: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.primary,
    marginTop: 4,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f3f4f6',
    borderRadius: 9999,
    paddingHorizontal: 4,
    paddingVertical: 4,
    gap: 8,
  },
  quantityButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 2,
  },
  disabledQuantityButton: {
    opacity: 0.5,
  },
  quantityIcon: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.primary,
  },
  quantityInput: {
    width: 20,
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    color: COLORS.textPrimary,
  },
  tipSection: {
    marginTop: 24,
    paddingHorizontal: 16,
  },
  tipCard: {
    padding: 16,
    borderRadius: 12,
  },
  tipTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  tipDesc: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  tipButtons: {
    flexDirection: 'row',
    gap: 12,
    paddingTop: 16,
    flexWrap: 'wrap',
  },
  tipButtonUnselected: {
    height: 36,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: COLORS.white,
    borderRadius: 9999,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tipButtonSelected: {
    height: 36,
    borderWidth: 1,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary,
    borderRadius: 9999,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tipButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  tipButtonSelectedText: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.white,
  },
  addressSection: {
    marginTop: 24,
    paddingHorizontal: 16,
  },
  addressCard: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 5,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  addressContent: {
    flex: 1,
  },
  addressTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  addressText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: 8,
  },
  changeButton: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.primary,
    marginLeft: 8,
  },
  subtotalSection: {
    marginTop: 24,
    paddingHorizontal: 16,
  },
  subtotalCard: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 5,
    gap: 12,
  },
  subtotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  taxLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  subtotalLabel: {
    fontSize: 14,
    color: COLORS.muted || '#9CA3AF',
    fontWeight: '800',
  },
  subtotalValue: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  dashedBorder: {
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    borderStyle: 'dashed',
    marginVertical: 12,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  gradientTextContainer: {
    borderRadius: 4,
  },
  gradientText: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.white,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    paddingVertical: 12,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 10,
  },
  footerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  paymentSelector: {
    flex: 1,
  },
  paymentSelectedContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  paymentUnselectedContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  paymentIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: `${COLORS.primary}10`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentTextInfo: {
    flex: 1,
  },
  payUsingText: {
    fontSize: 10,
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  paymentMethodName: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  selectPaymentText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  proceedLink: {
    flex: 1,
    height: 50,
    borderRadius: 12,
    overflow: 'hidden',
  },
  proceedLinkDisabled: {
    opacity: 0.7,
  },
  proceedGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  proceedContent: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  totalAmount: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.white,
    lineHeight: 20,
  },
  proceedLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: `${COLORS.white}CC`,
    textTransform: 'uppercase',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  modalCloseButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalScrollView: {
    flex: 1,
    padding: 16,
  },
  noAddressContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
    gap: 16,
  },
  noAddressTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  noAddressSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
  addressItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 5,
  },
  addressItemSelected: {
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  addressItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  addressItemDetails: {
    flex: 1,
  },
  addressItemName: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  addressItemText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 4,
  },
  addressItemContact: {
    fontSize: 14,
    color: COLORS.primary,
    fontWeight: '800',
  },
  defaultLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.primary,
  },
  modalFooter: {
    padding: 16,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  addAddressButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  addAddressText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '800',
  },
});
